### ISSUE TITLE
Directions outdated

### ISSUE THREAD

**Issue by res0o76i** [learn-co-curriculum/phase-0-html-album-cover-lab#15]
### Canvas Link

https://learning.flatironschool.com/courses/4318/assignments/120983?module_item_id=250683

### Concern

It states to run rspec and bundle for testing but there is no gem file and not a ruby lab.

**Comment by lizbur10** [comment]
Hi @res0o76i ! So sorry for the inconvenience! This is happening because you are in an older Prework course. The Prework was substantially revised a few months ago but unfortunately it wasn't possible to update the existing Canvas courses because the updates would have caused breaking changes for students who had already started Prework. The GitHub repos of the updated lessons and labs have been updated, but the lessons on Canvas have not. That's why you're seeing a mismatch.

As you continue through the prework, please disregard any instructions you see to run `rspec` and continue using `npm install` and `npm test` to run your tests. If you run into any difficulties, you can use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in
Canvas to connect with a Technical Coach on the Academic Success Team. 💙
