### ISSUE TITLE
Prework: Album cover lab

### ISSUE THREAD

**Issue by pithlyx** [learn-co-curriculum/phase-0-html-album-cover-lab#24]
### Canvas Link

https://learning.flatironschool.com/courses/6796/assignments/234931?module_item_id=551224

### Concern

im unable to actually run the code to view the web page, getting the error "crbug/1173575, non-JS module files deprecated." in the debug console. when trying to run the index file in chrome, mocha verified that the code is correct for the assignment so i submitted it anyway.

**Comment by Matt-Eva** [comment]
Thanks for raising this issue. Based on your description, it sounds like the
issue may be related to how you're interacting with your code rather than with the lesson
itself or the instructions. The curriculum team monitors these issues so that we
can fix typos and bugs in the curriculum, but we aren't equipped to provide
support.

To get help with your question, you should either:

- Reach out to your instructor (if you've started the program and have an
  instructor)
- Use the
  [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit)
  feature in Canvas to connect with a Technical Coach on the Academic Success
  Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
